export const taskGroupsData: any[] = [
  {
    iconName: 'briefcase',
    iconColor: '#ec4899',
    iconBg: '#fbcfe8',
    title: 'Office Project',
    subtitle: 'Grocery shopping app design',
    tasks: 23,
    progress: 70,
    cardColor: '#fff',
    progressColor: '#ec4899',
    time: '10:00 AM',
    status: 'done' as 'done',
  },
  {
    iconName: 'hexagon-multiple',
    iconColor: '#a78bfa',
    iconBg: '#ede9fe',
    title: 'Personal Project',
    subtitle: 'Personal development tasks',
    tasks: 30,
    progress: 42,
    cardColor: '#fff',
    progressColor: '#a78bfa',
    time: '12:00 PM',
    status: 'in-progress' as 'in-progress',
  },
  {
    iconName: 'book-open-variant',
    iconColor: '#f59e42',
    iconBg: '#fde68a',
    title: 'Daily Study',
    subtitle: 'Learning and research tasks',
    tasks: 30,
    progress: 87,
    cardColor: '#fff',
    progressColor: '#f59e42',
    time: '07:00 PM',
    status: 'to-do' as 'to-do',
  },
  {
    iconName: 'dumbbell',
    iconColor: '#ec4899',
    iconBg: '#fbcfe8',
    title: 'Gym',
    subtitle: 'Fitness and workout routine',
    tasks: 30,
    progress: 57,
    cardColor: '#fff',
    progressColor: '#ec4899',
    time: '06:00 AM',
    status: 'done' as 'done',
  },
  {
    iconName: 'home',
    iconColor: '#ec4899',
    iconBg: '#fbcfe8',
    title: 'Home',
    subtitle: 'Household chores and maintenance',
    tasks: 30,
    progress: 57,
    cardColor: '#fff',
    progressColor: '#ec4899',
    time: '08:00 PM',
    status: 'to-do' as 'to-do',
  },
  {
    iconName: 'car',
    iconColor: '#ec4899',
    iconBg: '#fbcfe8',
    title: 'Car',
    subtitle: 'Vehicle maintenance and travel',
    tasks: 30,
    progress: 57,
    cardColor: '#fff',
    progressColor: '#ec4899',
    time: '09:00 AM',
    status: 'in-progress' as 'in-progress',
  }
]; 